#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mesa
Version  : 19.0+2886.gbaf59e40cd1
Release  : 197
URL      : https://gitlab.freedesktop.org/mesa/mesa/-/archive/baf59e40cd1c3d19b299e5ac6bdf3af9e241c6b2/mesa-19.0+2886-gbaf59e40cd1.tar.bz2
Source0  : https://gitlab.freedesktop.org/mesa/mesa/-/archive/baf59e40cd1c3d19b299e5ac6bdf3af9e241c6b2/mesa-19.0+2886-gbaf59e40cd1.tar.bz2
Summary  : An open-source implementation of the OpenGL specification
Group    : Development/Tools
License  : MIT
BuildRequires : Mako-python
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Loader-dev32
BuildRequires : Vulkan-Tools
BuildRequires : bison
BuildRequires : buildreq-meson
BuildRequires : buildreq-scons
BuildRequires : elfutils-dev32
BuildRequires : expat-dev
BuildRequires : expat-dev32
BuildRequires : flex
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libX11-dev32
BuildRequires : libXv-dev
BuildRequires : libXv-dev32
BuildRequires : libgcrypt-dev
BuildRequires : libpthread-stubs-dev
BuildRequires : libunwind-dev32
BuildRequires : libva-dev
BuildRequires : llvm-dev
BuildRequires : llvm-dev32
BuildRequires : nettle-dev
BuildRequires : nettle-dev32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32dri3proto)
BuildRequires : pkgconfig(32libdrm_intel)
BuildRequires : pkgconfig(32xdamage)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xfixes)
BuildRequires : pkgconfig(32xrandr)
BuildRequires : pkgconfig(32xshmfence)
BuildRequires : pkgconfig(32xvmc)
BuildRequires : pkgconfig(32xxf86vm)
BuildRequires : pkgconfig(dri3proto)
BuildRequires : pkgconfig(libdrm_intel)
BuildRequires : pkgconfig(presentproto)
BuildRequires : pkgconfig(xdamage)
BuildRequires : pkgconfig(xfixes)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xshmfence)
BuildRequires : pkgconfig(xvmc)
BuildRequires : pkgconfig(xxf86vm)
BuildRequires : wayland-dev
BuildRequires : wayland-dev32
BuildRequires : wayland-protocols-dev
Patch1: avx2-drivers.patch

%description
New IR, or NIR, is an IR for Mesa intended to sit below GLSL IR and Mesa IR.
Its design inherits from the various IRs that Mesa has used in the past, as
well as Direct3D assembly, and it includes a few new ideas as well. It is a
flat (in terms of using instructions instead of expressions), typeless IR,
similar to TGSI and Mesa IR.  It also supports SSA (although it doesn't require
it).

%prep
%setup -q -n mesa-baf59e40cd1c3d19b299e5ac6bdf3af9e241c6b2
%patch1 -p1
pushd ..
cp -a mesa-baf59e40cd1c3d19b299e5ac6bdf3af9e241c6b2 build32
popd
pushd ..
cp -a mesa-baf59e40cd1c3d19b299e5ac6bdf3af9e241c6b2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555519226
unset LD_AS_NEEDED
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain -Dplatforms=x11,drm,wayland,surfaceless \
-Ddri3=true \
-Ddri-drivers=i915,i965,nouveau,r100,r200 \
-Dgallium-drivers=radeonsi,r600,nouveau,svga,swrast \
-Dcpp_std=gnu++11 \
-Dgallium-va=true \
-Dgallium-xa=true \
-Dvulkan-drivers=intel,amd \
-Dshared-glapi=true \
-Dgles2=true \
-Dgbm=true \
-Dopengl=true \
-Dglx=dri \
-Degl=true \
-Dglvnd=false \
-Dasm=true \
-Dllvm=true \
-Dshared-llvm=true \
-Dselinux=false \
-Dosmesa=gallium \
-Dgallium-xvmc=true \
-Db_ndebug=true  builddir
ninja -v -C builddir
pushd ../build32
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32"
meson --libdir=/usr/lib32 --prefix /usr --buildtype=plain -Dplatforms=x11,drm,wayland,surfaceless \
-Ddri3=true \
-Ddri-drivers=i915,i965,nouveau,r100,r200 \
-Dgallium-drivers=radeonsi,r600,nouveau,svga,swrast \
-Dcpp_std=gnu++11 \
-Dgallium-va=true \
-Dgallium-xa=true \
-Dvulkan-drivers=intel,amd \
-Dshared-glapi=true \
-Dgles2=true \
-Dgbm=true \
-Dopengl=true \
-Dglx=dri \
-Degl=true \
-Dglvnd=false \
-Dasm=true \
-Dllvm=true \
-Dshared-llvm=true \
-Dselinux=false \
-Dosmesa=gallium \
-Dgallium-xvmc=true \
-Db_ndebug=true  builddir
ninja -v -C builddir
popd

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mesa
cp docs/license.html %{buildroot}/usr/share/package-licenses/mesa/docs_license.html
cp src/imgui/LICENSE.txt %{buildroot}/usr/share/package-licenses/mesa/src_imgui_LICENSE.txt
cp src/mapi/glapi/gen/license.py %{buildroot}/usr/share/package-licenses/mesa/src_mapi_glapi_gen_license.py
pushd ../build32
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
DESTDIR=%{buildroot} ninja -C builddir install
## install_append content
mv %{buildroot}/usr/lib64/dri/haswell/i965_dri.so %{buildroot}/usr/lib64/dri/i965_dri.so.avx2
rm -rf  %{buildroot}/usr/lib64/haswell
## install_append end

%files
%defattr(-,root,root,-)
